// useVehicleListing — fetch a single vehicle listing by slug (preferred) or id.
//
// The public route is migrating from /gielda/ogloszenie/:id to /gielda/ogloszenie/:slug
// (Sprint 1 / A3). This hook accepts whatever is in the URL param and resolves it:
//   - a UUID  → look up by `id` (legacy links keep working)
//   - anything else → look up by `slug`
// with a cross-fallback so neither old nor new links 404 during the transition.
//
// Slugs are generated/owned by the DB trigger added in
// supabase/migrations/20260616120000_vehicle_listings_slug.sql.

import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type VehicleListingRow = Record<string, unknown> & { id: string; slug: string | null };

// `slug` is a fresh column not yet present in the auto-generated Supabase types,
// so query by it through a loosely-typed builder (types.ts is regenerated by Lovable).
async function selectBy(column: "id" | "slug", value: string): Promise<VehicleListingRow | null> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase.from("vehicle_listings") as any)
    .select("*")
    .eq(column, value)
    .maybeSingle();
  if (error) throw error;
  return (data as VehicleListingRow | null) ?? null;
}

async function fetchVehicleListing(param: string): Promise<VehicleListingRow | null> {
  const isUuid = UUID_RE.test(param);
  const primary = await selectBy(isUuid ? "id" : "slug", param);
  if (primary) return primary;
  // Cross-fallback: a non-UUID that is actually an id, or vice versa.
  return selectBy(isUuid ? "slug" : "id", param);
}

/**
 * @param param The `:slug` (or legacy `:id`) URL param.
 */
export function useVehicleListing(param: string | undefined) {
  return useQuery({
    queryKey: ["vehicle-listing", param],
    queryFn: () => fetchVehicleListing(param!),
    enabled: !!param,
  });
}
