INSERT INTO public.service_categories (name, slug, icon, is_active, sort_order) VALUES
('Fryzjer', 'fryzjer', 'sparkles', true, 30),
('Kosmetyczka', 'kosmetyczka', 'sparkles', true, 31),
('Paznokcie', 'paznokcie', 'sparkles', true, 32),
('Rzęsy i brwi', 'rzesy-brwi', 'sparkles', true, 33),
('Spa i masaż', 'spa-masaz', 'flower', true, 34),
('Barber', 'barber', 'sparkles', true, 35),
('Lekarze', 'lekarz', 'shield', true, 40),
('Dentyści', 'dentysta', 'shield', true, 41),
('Fizjoterapeuci', 'fizjoterapeuta', 'shield', true, 42),
('Psycholodzy', 'psycholog', 'shield', true, 43),
('Dietetycy', 'dietetyk', 'flower', true, 44),
('Prawnicy', 'prawnik', 'shield', true, 50),
('Księgowi', 'ksiegowy', 'pen-tool', true, 51),
('Doradcy finansowi', 'doradca-finansowy', 'pen-tool', true, 52),
('Notariusze', 'notariusz', 'pen-tool', true, 53),
('Tłumacze', 'tlumacz', 'pen-tool', true, 54),
('Kurierzy', 'kurier', 'truck', true, 60),
('Transport', 'transport', 'truck', true, 61),
('Przewóz osób', 'przewoz-osob', 'truck', true, 62),
('Stolarz', 'stolarz', 'hammer', true, 70),
('Malarz', 'malarz', 'pen-tool', true, 71),
('Glazurnik', 'glazurnik', 'hammer', true, 72),
('Dekarz', 'dekarz', 'hard-hat', true, 73),
('Klimatyzacja i pompy ciepła', 'klimatyzacja-dom', 'zap', true, 74)
ON CONFLICT (slug) DO NOTHING;