ALTER TABLE real_estate_listings
ADD COLUMN IF NOT EXISTS ai_rooms_data JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS ai_amenities JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ai_building_info JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ai_location_details JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ai_description_html TEXT,
ADD COLUMN IF NOT EXISTS ai_summary TEXT,
ADD COLUMN IF NOT EXISTS ai_area_total NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS ai_parsed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS ai_confidence INTEGER;